version: '3.8'

x-airflow-common: &airflow-common
  image: apache/airflow:2.10.3-python3.10
  restart: always
  environment: &airflow-env
    
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}

    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
    AIRFLOW__WEBSERVER__SESSION_LIFETIME: ${AIRFLOW__WEBSERVER__SESSION_LIFETIME}
    AIRFLOW_UID: ${AIRFLOW_UID}

    # Thêm biến môi trường GOOGLE_APPLICATION_CREDENTIALS cho Google BigQuery
    GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./keys:/opt/airflow/keys
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: >
      -c "airflow db init && airflow users create
      --username ${AIRFLOW_USERNAME}
      --firstname ${AIRFLOW_FIRSTNAME}
      --lastname ${AIRFLOW_LASTNAME}
      --role Admin
      --email ${AIRFLOW_EMAIL}
      --password ${AIRFLOW_PASSWORD}"
    depends_on:
      - postgres

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "9090:8080"
    depends_on:
      - airflow-init

  scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - airflow-init

volumes:
  postgres_data:
